export interface DaysTableProps {
  year?: number;
  month?: number;
  notes?: string;
}
export default function DaysTable({
  year = new Date().getFullYear(),
  month = new Date().getMonth(),
  notes = "",
}: DaysTableProps) {
  return (
    <table
      border={1}
      style={{ marginLeft: "auto", marginRight: "auto", width: "700px" }}
    >
      <thead>
        <tr
          style={{
            backgroundColor: "rgb(221, 221, 221)",
            textAlign: "center",
            fontWeight: "bold",
          }}
        >
          <td colSpan={2}>1&ordm; TURNO</td>
          <td rowSpan={2}>DIA</td>
          <td colSpan={2}>2&ordm; TURNO</td>
        </tr>
        <tr
          style={{
            backgroundColor: "rgb(221, 221, 221)",
            textAlign: "center",
            fontWeight: "bold",
          }}
        >
          <td>ENTRADA</td>
          <td>SA&Iacute;DA</td>
          <td>ENTRADA</td>
          <td>SA&Iacute;DA</td>
        </tr>
      </thead>
      <tbody style={{ textAlign: "center" }}>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>1</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>2</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>3</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>4</td>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>
            <strong>SÁBADO</strong>
          </td>
        </tr>
        <tr>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>5</td>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>
            <strong>DOMINGO</strong>
          </td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>6</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>7</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>8</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>9</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>10</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>11</td>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>
            <strong>SÁBADO</strong>
          </td>
        </tr>
        <tr>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>12</td>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>
            <strong>DOMINGO</strong>
          </td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>13</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>14</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>15</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>16</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>17</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>18</td>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>
            <strong>SÁBADO</strong>
          </td>
        </tr>
        <tr>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>19</td>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>
            <strong>DOMINGO</strong>
          </td>
        </tr>
        <tr>
          <td>
            <strong>FERIADO</strong>
          </td>
          <td>
            <strong>FERIADO</strong>
          </td>
          <td>20</td>
          <td>
            <strong>FERIADO</strong>
          </td>
          <td>
            <strong>FERIADO</strong>
          </td>
        </tr>
        <tr>
          <td>
            <strong>FERIADO</strong>
          </td>
          <td>
            <strong>FERIADO</strong>
          </td>
          <td>21</td>
          <td>
            <strong>FERIADO</strong>
          </td>
          <td>
            <strong>FERIADO</strong>
          </td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>22</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>23</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>08:00</td>
          <td>12:00</td>
          <td>24</td>
          <td>14:00</td>
          <td>18:00</td>
        </tr>
        <tr>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>25</td>
          <td>
            <strong>SÁBADO</strong>
          </td>
          <td>
            <strong>SÁBADO</strong>
          </td>
        </tr>
        <tr>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>26</td>
          <td>
            <strong>DOMINGO</strong>
          </td>
          <td>
            <strong>DOMINGO</strong>
          </td>
        </tr>
        <tr>
          <td>08:00</td>
          <td></td>
          <td>27</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td>28</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td colSpan={5}>{notes}&nbsp;</td>
        </tr>
      </tbody>
    </table>
  );
}
